# The west manifest file for the Pinetime.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#
# You can create your own manifest files and put them in any
# repository you want, to create your own custom Pinetime installation.
# For example, you could create a manifest file in your own
# out-of-tree application directory, which would pull the pinetime repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new pinetime installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: pinetime

  remotes:
    - name: pinetime
      url-base: https://github.com/nordic-krch
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch

  # The list of external projects for the Pinetime.
  #
  projects:
    - name: nrf
      repo-path: fw-nrfconnect-nrf
      revision: a955d411cdb8d9abd862342823df8bfefeaf4d6a
      remote: ncs
    - name: zephyr
      repo-path: fw-nrfconnect-zephyr
      west-commands: scripts/west-commands.yml
      revision: 3c75196149f876b4d40e490607d80591e60d467f
      remote: ncs
    - name: nffs
      revision: 00dd4fab1a00f2f6e995ef3f2e7c3814689f8885
      path: modules/fs/nffs
      remote: zephyrproject
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger
      remote: zephyrproject
    - name: mbedtls
      path: modules/crypto/mbedtls
      revision: 3776c158fe138a72c97c187e4d31c81c37884be9
      remote: zephyrproject
    - name: mcuboot
      repo-path: fw-nrfconnect-mcuboot
      revision: 2332c4cfd6aa32eadef3346b8616be9908309335
      path: bootloader/mcuboot
      remote: ncs
    - name: mcumgr
      repo-path: fw-nrfconnect-mcumgr
      revision: 706394b33ed21870b7a2e3df209bf769379f1cb7
      path: modules/lib/mcumgr
      remote: ncs
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 0fc68fceacd1efc1ce809c5880c380f3d98b7b6e
      remote: zephyrproject
    - name: ci-tools
      path: tools/ci-tools
      revision: e6b2e622ff726b9c43b9966e0bb1659623566e59
      remote: zephyrproject
    - name: net-tools
      path: tools/net-tools
      revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
      remote: zephyrproject
    - name: nrfxlib
      path: nrfxlib
      revision: 3e381d09f1d305e230435f5b6e4c9ef928b6a697
      remote: ncs
    - name: cmock
      path: test/cmock
      revision: c243b9a7a7b3c471023193992b46cf1bd1910450
      remote: throwtheswitch
    - name: unity
      path: test/cmock/vendor/unity
      revision: 031f3bbe45f8adf504ca3d13e6f093869920b091
      remote: throwtheswitch
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: mbedtls
      revision: mbedtls-2.16.3
      remote: armmbed
    - name: fatfs
      path: modules/fs/fatfs
      remote: zephyrproject
      revision: 0c1288bb817c1976388e0f55e8483f671ae437ab
    - name: hal_nordic
      path: modules/hal/nordic
      remote: zephyrproject
      revision: 8506c348b6da91a9f53bcbb181ecd82b752b9eed
    - name: lvgl
      path: modules/lib/gui/lvgl
      remote: zephyrproject
      revision: 74fc2e753a997bd71cefa34dd9c56dcb954b42e2
    - name: nrf_hw_models
      path: modules/bsim_hw_models/nrf_hw_models
      remote: zephyrproject
      revision: fec69703cb1ca06fcdab6d5fde01274f0fc5c759
    - name: littlefs
      path: modules/fs/littlefs
      remote: zephyrproject
      revision: fe9572dd5a9fcf93a249daa4233012692bd2881d

  self:
    path: pinetime
